---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Ziheng Zhong
  - Charles Cai
thanks: "Code and data are available at: https://github.com/iJustinn/Effect_of_Charter_Schools_on_School_Segregation.git"
date: today
date-format: long
abstract: "Write after we have the results"
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```



# Introduction

In recent years, charter schools have become a popular choice for families looking for alternatives to traditional public schools in the United States. These schools are praised by many for offering new opportunities for education improvement, suggesting that they can lead to better student performance by encouraging competition among schools. Research has shown that charter schools can indeed help students achieve higher test scores. However, not all parents choose schools based on their effectiveness alone, which can lead to increased differences in school quality and potentially make educational inequality worse.

An important issue in American education is the ongoing problem of racial segregation in schools, a problem that persists over 65 years since the historic Brown v. Board of Education decision aimed to end it. The question then arises: how do charter schools, which allow families to choose their schools, affect this racial divide? The answer is not straightforward. On one hand, charter schools could help mix students from different backgrounds by not tying school attendance to where a family lives, which often reflects racial divisions. On the other hand, if families select schools based on racial preferences or other factors, charter schools could actually make segregation worse.

While some charter schools aim to serve underrepresented communities, the overall impact of charter schools on racial segregation in public schools has been unclear and somewhat contested. Previous research on this topic has been mixed, with some studies suggesting charter schools might concentrate minority students more than traditional public schools do, while others find little difference in racial isolation between charter and traditional schools.

This paper aims to shed light on this issue by providing detailed analysis on whether charter schools contribute to or alleviate racial segregation in public schools. We use a large dataset covering nearly all public schools in the country from 1998 to 2018 to examine how the presence of charter schools affects the racial makeup of schools. Our study looks at how these effects play out across different regions and for different racial and ethnic groups, using sophisticated methods to ensure our findings are reliable.

We find that the expansion of charter schools has, on average, led to more segregation among racial and ethnic groups in schools, particularly in urban areas with large Black and Hispanic populations. However, the situation is complex, as charter schools also seem to bring some level of integration across larger geographic areas like metropolitan regions.

Our research contributes to the ongoing debate on the role of charter schools in American education, highlighting the need for careful consideration of how school choice impacts racial segregation. While charter schools have the potential to offer important benefits, it's crucial to understand and address the unintended consequences they may have on racial dynamics within the education system.



The remainder of this paper is structured as follows. @sec-data....



# Data {#sec-data}

Some of our data is of penguins (@fig-bills), from @palmerpenguins.



# Model

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in [Appendix -@sec-model-details].



## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_i$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters.  



### Model justification



# Results



# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check



## Diagnostics



\newpage


# References


